apiVersion: v1
kind: Service
metadata:
  name: namegame-challenge-svc
  labels:
    app: namegame-challenge
spec:
  type: NodePort
  ports:
  - port: 8082
    nodePort: 30001
  selector:
    app: namegame-challenge
