spring:
  application:
    name: namegame-svc
  data:
    mongodb:
      host: namegame-db-mongodb
      ##host: localhost -- for connecting to local MongoDB instance or if the app is running outside minikube and MongoDB inside minikube with port forwarding
      port: 27017
      database: namegame-db
      username: namegame
      password: willowtree

server:
  port: 8082
  servlet:
    context-path: /namegame

logging:
  level:
    root: DEBUG
    com.willowtree.test: INFO

namegame-svc:
  default:
    name-options: 6
    image-options: 6
  url: https://www.willowtreeapps.com/api/v1.0/profiles

